import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated test reports.
    "coverage/**",
    "playwright-report/**",
    // Generated by Orval from the OpenAPI snapshot; CI diff-gates it instead.
    "src/api/generated/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
