/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  $schema: "./node_modules/@stryker-mutator/core/schema/stryker-schema.json",
  plugins: ["@stryker-mutator/vitest-runner"],
  testRunner: "vitest",
  vitest: {
    configFile: "vitest.config.ts",
    related: true,
  },
  mutate: [
    "src/app/**/*.{ts,tsx}",
    "!src/app/**/*.test.{ts,tsx}",
    "!src/app/(app)/team/**",
    "!src/app/(app)/planner/**",
    "!src/app/(app)/tasks/**",
    "!src/app/(app)/finance/**",
    "!src/app/(app)/breeding/**",
    "!src/app/(app)/feeding/**",
    "!src/app/(app)/kidding/**",
    "!src/app/(app)/purchases/**",
    "!src/app/(app)/dashboard/**",
    "!src/app/(app)/milk/**",
    "!src/app/(app)/reports/**",
    "!src/app/(app)/buckets/**",
    "!src/app/(app)/app-layout-client.tsx",
    "!src/app/farm-select/**",
    "!src/app/login/**",
    "!src/app/register/**",
  ],
  reporters: ["clear-text", "progress-append-only", "json"],
  jsonReporter: { fileName: "reports/mutation/app2.json" },
  tempDirName: ".stryker-tmp-app2",
  ignorePatterns: [".stryker-tmp*/**", "reports/**", "coverage/**"],
  incremental: true,
  incrementalFile: "reports/stryker-app2-incremental.json",
  cleanTempDir: "always",
  concurrency: 8,
  ignoreStatic: true,
  dryRunTimeoutMinutes: 30,
  timeoutMS: 15000,
  thresholds: { high: 90, low: 80, break: 75 },
};

export default config;
