"""Full data model. All entities defined up-front per SPEC.

Split into per-domain submodules; this package re-exports every
name so existing ``from app.models import ...`` / ``from ..models import ...``
importers keep working unchanged.
"""

from ..db import Base
from .animals import Animal, BucketDefinition, BucketFeedSetting, BucketMove, WeightRecord
from .breeding import BreedingRecord, KiddingRecord, KidEntry
from .constants import (
    BREEDING_READY_BUCKETS,
    BUCK_DOE_RATIO,
    BUCK_ROTATION_DAYS,
    GESTATION_DAYS,
    HISTORY_OVERRIDE_REASON_PREFIX,
    KIDDING_WINDOW_DAYS,
    MAX_AGE_MONTHS,
    MAX_ANIMAL_TAG_LENGTH,
    MAX_BATCH_COUNT,
    MAX_FAILED_CYCLES_BEFORE_CULL,
    MAX_GESTATION_DAYS,
    MAX_RECUR_DAYS,
    MAX_TASK_TITLE_LENGTH,
    MAX_WITHDRAWAL_DAYS,
    MEAT_SALE_AGE_MONTHS,
    MEAT_SALE_WEIGHT_KG,
    MIN_BREEDING_AGE_MONTHS,
    MIN_BREEDING_WEIGHT_KG,
    MIN_BUCK_BREEDING_AGE_MONTHS,
    MIN_BUCK_BREEDING_WEIGHT_KG,
    MIN_GESTATION_DAYS,
    POSTPARTUM_RECOVERY_DAYS,
    PREGNANCY_LOSS_CAUSES,
    SHIFT_SPLIT,
    ULTRASOUND_AFTER_BREEDING_DAYS,
    VERIFICATION_REQUIRED_CATEGORIES,
    WEANING_DAYS,
)
from .core import Farm, FarmMembership, RefreshSession, Role, User
from .enums import (
    AnimalSource,
    AnimalStatus,
    BirthType,
    BreedingMethod,
    BreedingOutcome,
    Bucket,
    FarmType,
    FeedingShift,
    HealthEventType,
    IngredientCategory,
    KiddingEase,
    KidStatus,
    Sex,
    TaskCategory,
    TaskStatus,
    TransactionCategory,
    TransactionType,
)
from .feeding import FeedFinishedStock, FeedingRecord, FeedInventory, FeedRecipe, FeedRecipeLine
from .finance import Transaction
from .health import HealthEvent, MovementRestrictionAction, VaccineTemplate
from .helpers import (
    QUARANTINE_PROTOCOL,
    QuarantineTaskSpec,
    conception_rate,
    expected_kidding_date,
    planned_ultrasound_date,
    quarantine_schedule,
)
from .idempotency import IdempotencyRecord
from .milk import MilkRecord
from .purchases import PurchaseBatch
from .simulation import SimulationScenario
from .species import (
    BUFFALO_DAIRY,
    FARM_TYPE_LABELS,
    FARM_TYPES,
    GOAT,
    SPECIES_PROFILES,
    SpeciesProfile,
    species_profile,
)
from .tasks import Task

__all__ = [
    "BREEDING_READY_BUCKETS",
    "BUCK_DOE_RATIO",
    "BUCK_ROTATION_DAYS",
    "BUFFALO_DAIRY",
    "FARM_TYPES",
    "FARM_TYPE_LABELS",
    "GESTATION_DAYS",
    "GOAT",
    "HISTORY_OVERRIDE_REASON_PREFIX",
    "KIDDING_WINDOW_DAYS",
    "MAX_AGE_MONTHS",
    "MAX_ANIMAL_TAG_LENGTH",
    "MAX_BATCH_COUNT",
    "MAX_FAILED_CYCLES_BEFORE_CULL",
    "MAX_GESTATION_DAYS",
    "MAX_RECUR_DAYS",
    "MAX_TASK_TITLE_LENGTH",
    "MAX_WITHDRAWAL_DAYS",
    "MEAT_SALE_AGE_MONTHS",
    "MEAT_SALE_WEIGHT_KG",
    "MIN_BREEDING_AGE_MONTHS",
    "MIN_BREEDING_WEIGHT_KG",
    "MIN_BUCK_BREEDING_AGE_MONTHS",
    "MIN_BUCK_BREEDING_WEIGHT_KG",
    "MIN_GESTATION_DAYS",
    "POSTPARTUM_RECOVERY_DAYS",
    "PREGNANCY_LOSS_CAUSES",
    "QUARANTINE_PROTOCOL",
    "SHIFT_SPLIT",
    "SPECIES_PROFILES",
    "ULTRASOUND_AFTER_BREEDING_DAYS",
    "VERIFICATION_REQUIRED_CATEGORIES",
    "WEANING_DAYS",
    "Animal",
    "AnimalSource",
    "AnimalStatus",
    "Base",
    "BirthType",
    "BreedingMethod",
    "BreedingOutcome",
    "BreedingRecord",
    "Bucket",
    "BucketDefinition",
    "BucketFeedSetting",
    "BucketMove",
    "Farm",
    "FarmMembership",
    "FarmType",
    "FeedFinishedStock",
    "FeedInventory",
    "FeedRecipe",
    "FeedRecipeLine",
    "FeedingRecord",
    "FeedingShift",
    "HealthEvent",
    "HealthEventType",
    "IdempotencyRecord",
    "IngredientCategory",
    "KidEntry",
    "KidStatus",
    "KiddingEase",
    "KiddingRecord",
    "MilkRecord",
    "MovementRestrictionAction",
    "PurchaseBatch",
    "QuarantineTaskSpec",
    "RefreshSession",
    "Role",
    "Sex",
    "SimulationScenario",
    "SpeciesProfile",
    "Task",
    "TaskCategory",
    "TaskStatus",
    "Transaction",
    "TransactionCategory",
    "TransactionType",
    "User",
    "VaccineTemplate",
    "WeightRecord",
    "conception_rate",
    "expected_kidding_date",
    "planned_ultrasound_date",
    "quarantine_schedule",
    "species_profile",
]
