"""simulation scenarios

Revision ID: c4b72167db86
Revises: ed5efe13a516
Create Date: 2026-08-06 19:09:53.007159+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c4b72167db86"
down_revision: str | Sequence[str] | None = "ed5efe13a516"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_scenarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("assumptions", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("farm_id", "name", name="uq_simulation_scenario_per_farm"),
    )
    op.create_index(
        op.f("ix_simulation_scenarios_farm_id"), "simulation_scenarios", ["farm_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulation_scenarios_farm_id"), table_name="simulation_scenarios")
    op.drop_table("simulation_scenarios")
    # ### end Alembic commands ###
