"""initial schema

Revision ID: ed5efe13a516
Revises:
Create Date: 2026-08-05 20:36:25.732122+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ed5efe13a516"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bucket_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("who", sa.String(length=255), nullable=True),
        sa.Column("exit_rule", sa.String(length=255), nullable=True),
        sa.Column("daily_kg_per_head", sa.Float(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "feed_recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "vaccine_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("first_dose_age_months", sa.Float(), nullable=True),
        sa.Column("booster_weeks", sa.Float(), nullable=True),
        sa.Column("repeat_months", sa.Float(), nullable=True),
        sa.Column("timing_note", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "farms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feed_recipe_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient", sa.String(length=120), nullable=False),
        sa.Column("kg_per_100kg", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["feed_recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bucket_feed_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.String(length=20), nullable=False),
        sa.Column("daily_kg_per_head", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("farm_id", "bucket", name="uq_feed_setting_per_bucket"),
    )
    op.create_index(
        op.f("ix_bucket_feed_settings_farm_id"), "bucket_feed_settings", ["farm_id"], unique=False
    )
    op.create_table(
        "feed_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("ingredient", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("qty_on_hand", sa.Float(), nullable=False),
        sa.Column("reorder_level", sa.Float(), nullable=True),
        sa.Column("last_purchase_price_per_kg", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feed_inventory_farm_id"), "feed_inventory", ["farm_id"], unique=False)
    op.create_table(
        "feeding_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("shift", sa.String(length=10), nullable=False),
        sa.Column("bucket", sa.String(length=20), nullable=False),
        sa.Column("recipe_code", sa.String(length=30), nullable=True),
        sa.Column("qty_kg", sa.Float(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feeding_records_farm_id"), "feeding_records", ["farm_id"], unique=False
    )
    op.create_table(
        "purchase_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("supplier", sa.String(length=120), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("avg_age_months", sa.Float(), nullable=True),
        sa.Column("avg_weight_kg", sa.Float(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_batches_farm_id"), "purchase_batches", ["farm_id"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("permissions", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("farm_id", "name", name="uq_role_name_per_farm"),
    )
    op.create_index(op.f("ix_roles_farm_id"), "roles", ["farm_id"], unique=False)
    op.create_table(
        "animals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("tag_number", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("breed", sa.String(length=80), nullable=False),
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("estimated_dob", sa.Date(), nullable=True),
        sa.Column("birth_type", sa.String(length=10), nullable=True),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("purchase_price", sa.Float(), nullable=True),
        sa.Column("seller_name", sa.String(length=120), nullable=True),
        sa.Column("purchase_batch_id", sa.Integer(), nullable=True),
        sa.Column("dam_id", sa.Integer(), nullable=True),
        sa.Column("sire_id", sa.Integer(), nullable=True),
        sa.Column("birth_weight", sa.Float(), nullable=True),
        sa.Column("current_bucket", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("status_date", sa.Date(), nullable=True),
        sa.Column("status_notes", sa.String(length=255), nullable=True),
        sa.Column("sale_price", sa.Float(), nullable=True),
        sa.Column("buyer_name", sa.String(length=120), nullable=True),
        sa.Column("cull_candidate", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dam_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_batch_id"],
            ["purchase_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sire_id"],
            ["animals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("farm_id", "tag_number", name="uq_animal_tag_per_farm"),
    )
    op.create_index(op.f("ix_animals_farm_id"), "animals", ["farm_id"], unique=False)
    op.create_table(
        "farm_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "farm_id", name="uq_membership_user_farm"),
    )
    op.create_index(
        op.f("ix_farm_memberships_farm_id"), "farm_memberships", ["farm_id"], unique=False
    )
    op.create_index(
        op.f("ix_farm_memberships_user_id"), "farm_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "breeding_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("doe_id", sa.Integer(), nullable=False),
        sa.Column("buck_id", sa.Integer(), nullable=False),
        sa.Column("breeding_date", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("heat_cycle_number", sa.Integer(), nullable=False),
        sa.Column("ultrasound_date", sa.Date(), nullable=True),
        sa.Column("ultrasound_done", sa.Boolean(), nullable=False),
        sa.Column("pregnant", sa.Boolean(), nullable=True),
        sa.Column("kid_count_detected", sa.Integer(), nullable=True),
        sa.Column("expected_kidding_date", sa.Date(), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["buck_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doe_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_breeding_records_farm_id"), "breeding_records", ["farm_id"], unique=False
    )
    op.create_table(
        "bucket_moves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=False),
        sa.Column("from_bucket", sa.String(length=20), nullable=True),
        sa.Column("to_bucket", sa.String(length=20), nullable=False),
        sa.Column("moved_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bucket_moves_animal_id"), "bucket_moves", ["animal_id"], unique=False)
    op.create_table(
        "health_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=True),
        sa.Column("purchase_batch_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=12), nullable=False),
        sa.Column("product_name", sa.String(length=120), nullable=True),
        sa.Column("disease_target", sa.String(length=120), nullable=True),
        sa.Column("dose", sa.String(length=60), nullable=True),
        sa.Column("route", sa.String(length=20), nullable=True),
        sa.Column("vet_name", sa.String(length=120), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("next_due_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_batch_id"],
            ["purchase_batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_health_events_farm_id"), "health_events", ["farm_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("related_animal_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_animal_id"],
            ["animals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_farm_id"), "transactions", ["farm_id"], unique=False)
    op.create_table(
        "weight_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("bcs", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weight_records_animal_id"), "weight_records", ["animal_id"], unique=False
    )
    op.create_table(
        "kidding_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("doe_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("breeding_record_id", sa.Integer(), nullable=True),
        sa.Column("ease", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["breeding_record_id"],
            ["breeding_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doe_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("breeding_record_id", name="uq_kidding_breeding_record"),
    )
    op.create_index(
        op.f("ix_kidding_records_farm_id"), "kidding_records", ["farm_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("farm_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=True),
        sa.Column("purchase_batch_id", sa.Integer(), nullable=True),
        sa.Column("breeding_record_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=15), nullable=False),
        sa.Column("auto_generated", sa.Boolean(), nullable=False),
        sa.Column("assigned_role_id", sa.Integer(), nullable=True),
        sa.Column("assigned_user_id", sa.Integer(), nullable=True),
        sa.Column("completed_by_id", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("verified_by_id", sa.Integer(), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("verification_note", sa.String(length=255), nullable=True),
        sa.Column("recur_days", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["breeding_record_id"],
            ["breeding_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"],
            ["farms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_batch_id"],
            ["purchase_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_farm_id"), "tasks", ["farm_id"], unique=False)
    op.create_table(
        "kid_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kidding_record_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=50), nullable=True),
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("birth_weight", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("animal_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["animal_id"],
            ["animals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kidding_record_id"],
            ["kidding_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kid_entries")
    op.drop_index(op.f("ix_tasks_farm_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_kidding_records_farm_id"), table_name="kidding_records")
    op.drop_table("kidding_records")
    op.drop_index(op.f("ix_weight_records_animal_id"), table_name="weight_records")
    op.drop_table("weight_records")
    op.drop_index(op.f("ix_transactions_farm_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_health_events_farm_id"), table_name="health_events")
    op.drop_table("health_events")
    op.drop_index(op.f("ix_bucket_moves_animal_id"), table_name="bucket_moves")
    op.drop_table("bucket_moves")
    op.drop_index(op.f("ix_breeding_records_farm_id"), table_name="breeding_records")
    op.drop_table("breeding_records")
    op.drop_index(op.f("ix_farm_memberships_user_id"), table_name="farm_memberships")
    op.drop_index(op.f("ix_farm_memberships_farm_id"), table_name="farm_memberships")
    op.drop_table("farm_memberships")
    op.drop_index(op.f("ix_animals_farm_id"), table_name="animals")
    op.drop_table("animals")
    op.drop_index(op.f("ix_roles_farm_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_purchase_batches_farm_id"), table_name="purchase_batches")
    op.drop_table("purchase_batches")
    op.drop_index(op.f("ix_feeding_records_farm_id"), table_name="feeding_records")
    op.drop_table("feeding_records")
    op.drop_index(op.f("ix_feed_inventory_farm_id"), table_name="feed_inventory")
    op.drop_table("feed_inventory")
    op.drop_index(op.f("ix_bucket_feed_settings_farm_id"), table_name="bucket_feed_settings")
    op.drop_table("bucket_feed_settings")
    op.drop_table("feed_recipe_lines")
    op.drop_table("farms")
    op.drop_table("vaccine_templates")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("feed_recipes")
    op.drop_table("bucket_definitions")
    # ### end Alembic commands ###
