"""Pydantic schemas for the finance module."""

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from .common import (
    BoundedId,
    MoneyFloat,
    NonNegativeMoneyFloat,
    PastOrTodayDate,
    PostgresText,
    QuantityKgFloat,
    StrictInputModel,
)

TransactionTypeStr = Literal["INCOME", "EXPENSE"]
# Mirrors models.TransactionCategory exactly (v1 validated against the enum).
TransactionCategoryStr = Literal[
    "ANIMAL_SALE",
    "ANIMAL_PURCHASE",
    "FEED",
    "MEDICINE",
    "VET",
    "LABOUR",
    "EQUIPMENT",
    "MANURE",
    "OTHER",
]

# Categories the ledger only ever writes itself (animal exits and purchase
# batches carry their own audited provenance); a manual row in these
# categories would be indistinguishable from system-generated revenue.
SYSTEM_ONLY_CATEGORIES = frozenset({"ANIMAL_SALE", "ANIMAL_PURCHASE"})


class TransactionIn(StrictInputModel):
    date: PastOrTodayDate
    type: TransactionTypeStr
    category: TransactionCategoryStr
    amount: MoneyFloat
    # transactions.notes String(255)
    notes: PostgresText | None = Field(default=None, max_length=255)
    related_animal_id: BoundedId | None = None  # API verifies same-farm existence

    @model_validator(mode="after")
    def _manual_row_policy(self) -> "TransactionIn":
        if self.category in SYSTEM_ONLY_CATEGORIES:
            raise ValueError(
                f"{self.category} rows are generated by the animal purchase/sale "
                "workflow and cannot be created manually"
            )
        return self


class TransactionOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    date: date
    type: TransactionTypeStr
    category: TransactionCategoryStr
    amount: float
    notes: str | None
    related_animal_id: int | None
    animal_tag: str | None = None
    created_at: datetime
    source_type: str | None
    source_id: int | None
    correction_of_id: int | None
    voided_at: datetime | None
    voided_by_id: int | None
    void_reason: str | None


class TransactionCorrectionIn(StrictInputModel):
    """Audited replacement for an existing ledger row.

    Zero is allowed here so an erroneous system-generated amount can be
    neutralized without deleting its provenance.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    date: PastOrTodayDate
    type: TransactionTypeStr
    category: TransactionCategoryStr
    amount: NonNegativeMoneyFloat
    notes: PostgresText | None = Field(default=None, max_length=255)
    related_animal_id: BoundedId | None = None
    feed_quantity_kg: QuantityKgFloat | None = None
    reason: PostgresText = Field(min_length=3, max_length=255)


class PnlRowOut(BaseModel):
    month: str  # YYYY-MM
    income: float
    expense: float
    net: float
    categories: dict[str, dict[str, float]]


class MortalityMemoOut(BaseModel):
    """Ledger-neutral mortality visibility (audit backlog #31): deaths in the
    P&L window with an optional estimated loss. A memo — deliberately NOT a
    transaction and never part of the income/expense totals."""

    window_months: int
    head_count: int
    estimated_loss: float | None
    basis: str


class FinanceOut(BaseModel):
    transactions: list[TransactionOut]
    transactions_total: int
    limit: int
    offset: int
    total_income: float
    total_expense: float
    # Memo line, not an expense: the farm's feed stock valued at each
    # inventory item's last purchase price (qty_on_hand x last price). Kept
    # out of the income/expense totals above — an unsold stockpile is an
    # asset, not a transaction.
    feed_stock_value: float
    # Memo line, not an expense: deaths in the rolling P&L window, valued at
    # the farm's own realized ₹/kg when both weights and a weighed sale
    # exist. Kept out of the totals — a death books no cash flow.
    mortality_loss: MortalityMemoOut
    pnl: list[PnlRowOut]


# Mirrors models.INSURANCE_POLICY_STATUSES exactly.
InsuranceStatusStr = Literal["active", "renewed", "lapsed", "claimed"]


class InsurancePolicyIn(StrictInputModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    # insurance_policies.policy_number String(60) / insurer String(120)
    policy_number: PostgresText = Field(min_length=1, max_length=60)
    insurer: PostgresText = Field(min_length=1, max_length=120)
    sum_insured: MoneyFloat
    premium: NonNegativeMoneyFloat
    start_date: PastOrTodayDate
    # A renewal is the whole point of a future-dated policy, so unlike
    # start_date it may lie ahead (the renewal duty is spawned from it).
    renewal_date: date
    animal_id: BoundedId | None = None  # API verifies same-farm existence
    notes: PostgresText | None = None

    @model_validator(mode="after")
    def _renewal_not_before_start(self) -> "InsurancePolicyIn":
        if self.renewal_date < self.start_date:
            raise ValueError("renewal_date cannot be before start_date")
        return self


class InsurancePolicyOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    policy_number: str
    insurer: str
    animal_id: int | None
    animal_tag: str | None = None
    sum_insured: float
    premium: float
    start_date: date
    renewal_date: date
    status: InsuranceStatusStr
    notes: str | None
    created_at: datetime


class InsuranceListOut(BaseModel):
    policies: list[InsurancePolicyOut]
    total: int


class InsuranceRenewalIn(StrictInputModel):
    """Move a policy forward: a new renewal horizon (never backwards) and an
    optional corrected premium. The policy keeps its identity and history —
    there is no edit/delete; renewal/lapse status is the register's version
    of the ledger's correction flow."""

    renewal_date: date
    premium: NonNegativeMoneyFloat | None = None


class InsuranceClaimIn(StrictInputModel):
    """Record a claim against a policy — the register's terminal event.

    A claim is a status fact, not a money movement: any payout the insurer
    settles is booked through the ledger like any other income."""

    claim_date: PastOrTodayDate | None = None  # defaults to today


class LifetimePnlOut(BaseModel):
    """Per-animal lifetime profit & loss (money in minus money out).

    Feed costs are deliberately absent: feed is purchased and dispensed at
    farm level, so any per-animal attribution would be a fabricated split."""

    animal_id: int
    tag_number: str
    purchase_cost: float
    health_cost: float
    insurance_premiums: float
    sale_income: float
    # income - (purchase_cost + health_cost + insurance_premiums)
    net: float
    note: str
