import { safeAppPath } from "@/lib/utils";

export type PermissionCheck = (permission: string) => boolean;

/** Subset of TaskOut consulted by the duty-board availability mirrors below. */
export interface TaskActionState {
  category: string;
  auto_generated: boolean;
  animal_id: number | null;
  purchase_batch_id: number | null;
  due_date: string;
}

/** Mirror of the deterministic 409 gates in backend `api/tasks.py::skip`, so
 * the board never offers a Skip that the server is certain to reject:
 * - Batch-linked generated duties are auditable quarantine gates and refuse a
 *   manual skip while the batch still holds an ACTIVE animal. Once the last
 *   batch animal is retired the backend sweeps those duties itself
 *   (`skip_pending_tasks_for_empty_batch`), so a PENDING one on screen
 *   implies a live batch — the skip can only 409.
 * - A generated WEANING duty, and a generated animal-linked BUCKET_MOVE duty,
 *   are each the only way out of the closed RECOVERY bucket for their doe/kids
 *   while pending (or the doe is inactive, which trips the linked-animal-
 *   active gate instead) — either branch is a guaranteed 409. BUCKET_MOVE also
 *   covers the pregnancy→DELIVERY move, which is legitimately skippable, but
 *   TaskOut carries no bucket state to tell the two flavors apart, and a
 *   guaranteed-409 dead click on the RECOVERY flavor is worse than graying out
 *   the rarer DELIVERY one, so both categories fail closed here. */
export function taskSkipUnavailable(task: TaskActionState): boolean {
  if (!task.auto_generated) return false;
  if (task.purchase_batch_id !== null) return true;
  return (
    (task.category === "WEANING" || task.category === "BUCKET_MOVE") && task.animal_id !== null
  );
}

/** Mirror of the linked-duty due-date guard in backend
 * `api/health.py::_record_event_mutation`: a linked event's date can never be
 * in the future and must not precede the duty's due date, so submitting the
 * form of a future-dated VACCINE/DEWORMING duty can only 409 ("not due yet")
 * until that day arrives. Ultrasound/kidding forms are exempt — recording an
 * early return-to-heat or an early kidding is legitimate. */
export function taskFormNotDueYet(task: TaskActionState, today: string): boolean {
  return (
    (task.category === "VACCINE" || task.category === "DEWORMING") &&
    task.due_date > today
  );
}

/** Task action URLs are generated by the backend, but opening their target
 * form also requires that module's manage permission. Unknown paths fail
 * closed even when they are otherwise safe same-origin application paths. */
export function permittedTaskActionPath(
  actionUrl: string | null | undefined,
  can: PermissionCheck,
): string | null {
  const rawPath = safeAppPath(actionUrl);
  // Backend-generated actions never contain encoded path separators or dot
  // segments. Reject them before URL normalization so an attacker-controlled
  // `/breeding/%2e%2e/finance` cannot borrow breeding.manage for /finance.
  if (!rawPath || /%(?:2e|2f|5c)/i.test(rawPath)) return null;
  const url = new URL(rawPath, "https://goatfarm.invalid");
  const path = url.pathname;
  const normalized = `${path}${url.search}${url.hash}`;
  if (path === "/breeding" || path.startsWith("/breeding/")) {
    return can("breeding.manage") ? normalized : null;
  }
  if (path === "/kidding" || path.startsWith("/kidding/")) {
    return can("kidding.manage") ? normalized : null;
  }
  if (path === "/health" || path.startsWith("/health/")) {
    return can("health.manage") ? normalized : null;
  }
  return null;
}
