import { safeAppPath } from "@/lib/utils";

export type PermissionCheck = (permission: string) => boolean;

/** Task action URLs are generated by the backend, but opening their target
 * form also requires that module's manage permission. Unknown paths fail
 * closed even when they are otherwise safe same-origin application paths. */
export function permittedTaskActionPath(
  actionUrl: string | null | undefined,
  can: PermissionCheck,
): string | null {
  const rawPath = safeAppPath(actionUrl);
  // Backend-generated actions never contain encoded path separators or dot
  // segments. Reject them before URL normalization so an attacker-controlled
  // `/breeding/%2e%2e/finance` cannot borrow breeding.manage for /finance.
  if (!rawPath || /%(?:2e|2f|5c)/i.test(rawPath)) return null;
  const url = new URL(rawPath, "https://goatfarm.invalid");
  const path = url.pathname;
  const normalized = `${path}${url.search}${url.hash}`;
  if (path === "/breeding" || path.startsWith("/breeding/")) {
    return can("breeding.manage") ? normalized : null;
  }
  if (path === "/kidding" || path.startsWith("/kidding/")) {
    return can("kidding.manage") ? normalized : null;
  }
  if (path === "/health" || path.startsWith("/health/")) {
    return can("health.manage") ? normalized : null;
  }
  return null;
}
